"""
@file panchayat_registry.py
@description Single canonical backend source of truth for Gram Panchayat metadata, coordinates,
             and primary crop phenological stages.
@module services/api
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from typing import Literal


@dataclass(frozen=True)
class PanchayatMetadata:
    """
    Canonical metadata definition for a Gram Panchayat pilot site or regional agromet station.
    """
    panchayat_id: str
    name: str
    name_hi: str
    district: str
    block: str
    latitude: float
    longitude: float
    elevation_m: float
    crop: str
    crop_hi: str
    crop_stage: str
    default_advisory_en: str
    default_advisory_hi: str
    # Optional. When known, the crop stage is estimated from growing-degree days since
    # this date instead of the static crop_stage above. Left unset for every registry
    # entry on purpose: no real sowing dates are on record, and inventing them would
    # pass fiction off as a GDD estimate. Supply it per request (?sowing_date=) instead.
    sowing_date: date | None = None


# ─────────────────────────────────────────────────────────────────────────────
#  Canonical Pilot & Multi-Region Agromet Registry (All 71 Domains)
# ─────────────────────────────────────────────────────────────────────────────

PILOT_PANCHAYAT_IDS = ["KADERA_001", "BHANKRI_002", "TUNGA_003", "DADHIKAR_004"]

PANCHAYAT_REGISTRY: dict[str, PanchayatMetadata] = {
    "KADERA_001": PanchayatMetadata(
        panchayat_id="KADERA_001",
        name="Kadera",
        name_hi="काडेरा",
        district="Jaipur",
        block="Chaksu",
        latitude=26.9124,
        longitude=75.7873,
        elevation_m=431.0,
        crop="Pearl Millet (Bajra)",
        crop_hi="बाजरा",
        crop_stage="Flowering",
        default_advisory_en="Postpone urea top-dressing and sprays for 36 hours. Open drainage channels in low plots.",
        default_advisory_hi="अगले 36 घंटे यूरिया और दवा छिड़काव स्थगित करें। निचले खेतों में जल निकासी नालियां खोलें।",
    ),
    "BHANKRI_002": PanchayatMetadata(
        panchayat_id="BHANKRI_002",
        name="Bhankri",
        name_hi="भांकरी",
        district="Jaipur",
        block="Chaksu",
        latitude=26.8761,
        longitude=75.8512,
        elevation_m=398.0,
        crop="Mustard (Sarson)",
        crop_hi="सरसों",
        crop_stage="Flowering",
        default_advisory_en="Spray after 10:00 tomorrow when winds settle. Complete mustard sowing today.",
        default_advisory_hi="कल सुबह 10 बजे के बाद हवा शांत होने पर छिड़काव करें। आज सरसों की बुवाई पूरी करें।",
    ),
    "TUNGA_003": PanchayatMetadata(
        panchayat_id="TUNGA_003",
        name="Tunga",
        name_hi="टूंगा",
        district="Jaipur",
        block="Bassi",
        latitude=26.8562,
        longitude=75.9419,
        elevation_m=442.0,
        crop="Guar (Cluster bean)",
        crop_hi="ग्वार",
        crop_stage="Vegetative",
        default_advisory_en="Favourable for interculturing for 48 hours. Irrigate young guar in the evening.",
        default_advisory_hi="अगले 48 घंटे निराई-गुड़ाई के लिए अनुकूल। शाम को ग्वार की हल्की सिंचाई करें।",
    ),
    "DADHIKAR_004": PanchayatMetadata(
        panchayat_id="DADHIKAR_004",
        name="Dadhikar",
        name_hi="दाधीकर",
        district="Alwar",
        block="Umren",
        latitude=27.6180,
        longitude=76.5620,
        elevation_m=320.0,
        crop="Groundnut",
        crop_hi="मूंगफली",
        crop_stage="Pegging",
        default_advisory_en="Stop all spraying for 48 hours — squalls likely. Cover harvested pods with tarpaulin.",
        default_advisory_hi="48 घंटे कीटनाशक छिड़काव रोकें — आंधी संभावित। कटी मूंगफली को तिरपाल से ढकें।",
    ),
    "CHAKSU_009": PanchayatMetadata(
        panchayat_id="CHAKSU_009",
        name="Chaksu",
        name_hi="चाकसू",
        district="Jaipur",
        block="Chaksu",
        latitude=26.605,
        longitude=75.95,
        elevation_m=410.0,
        crop="Mustard (Sarson)",
        crop_hi="सरसों",
        crop_stage="Vegetative",
        default_advisory_en="Moisture levels favorable for mustard seedling emergence.",
        default_advisory_hi="नमी का स्तर अनुकूल है। सरसों की बुवाई आगे बढ़ाएं।",
    ),
    "BASSI_010": PanchayatMetadata(
        panchayat_id="BASSI_010",
        name="Bassi",
        name_hi="बस्सी",
        district="Jaipur",
        block="Bassi",
        latitude=26.832,
        longitude=76.042,
        elevation_m=425.0,
        crop="Chickpea (Chana)",
        crop_hi="चना",
        crop_stage="Vegetative",
        default_advisory_en="Field preparation for chickpea. Deep plowing recommended.",
        default_advisory_hi="चना बुवाई के लिए खेत तैयार करें। गहरी जुताई करें।",
    ),
    "CHOMU_011": PanchayatMetadata(
        panchayat_id="CHOMU_011",
        name="Chomu",
        name_hi="चौमूं",
        district="Jaipur",
        block="Chomu",
        latitude=27.17,
        longitude=75.72,
        elevation_m=395.0,
        crop="Vegetables & Ber",
        crop_hi="सब्जियां",
        crop_stage="Vegetative",
        default_advisory_en="Maintain drip fertigation schedule for vegetable and Ber orchards.",
        default_advisory_hi="बेर के बगीचों में ड्रिप सिंचाई चालू रखें।",
    ),
    "JOBNER_012": PanchayatMetadata(
        panchayat_id="JOBNER_012",
        name="Jobner",
        name_hi="जोबनेर",
        district="Jaipur",
        block="Jobner",
        latitude=26.97,
        longitude=75.38,
        elevation_m=405.0,
        crop="Pearl Millet (Bajra)",
        crop_hi="बाजरा",
        crop_stage="Vegetative",
        default_advisory_en="Agronomy guidance: Termite treatment recommended for sandy soil plots.",
        default_advisory_hi="कृषि विश्वविद्यालय सिफारिश: दीमक नियंत्रण हेतु क्लोरपायरीफॉस का प्रयोग करें।",
    ),
    "SHAHPURA_013": PanchayatMetadata(
        panchayat_id="SHAHPURA_013",
        name="Shahpura",
        name_hi="शाहपुरा",
        district="Jaipur",
        block="Shahpura",
        latitude=27.39,
        longitude=75.96,
        elevation_m=415.0,
        crop="Mustard (Sarson)",
        crop_hi="सरसों",
        crop_stage="Vegetative",
        default_advisory_en="Seed treatment recommended before sowing for fungal blight resistance.",
        default_advisory_hi="सरसों में तना गलन रोग की रोकथाम हेतु बीज उपचार अवश्य करें।",
    ),
    "KOTPUTLI_014": PanchayatMetadata(
        panchayat_id="KOTPUTLI_014",
        name="Kotputli",
        name_hi="कोटपूतली",
        district="Kotputli-Behror",
        block="Kotputli",
        latitude=27.7,
        longitude=76.2,
        elevation_m=375.0,
        crop="Wheat (HD 2967)",
        crop_hi="गेहूं",
        crop_stage="Vegetative",
        default_advisory_en="Complete final cotton picking and prepare fields for timely wheat sowing.",
        default_advisory_hi="कपास की चुगाई पूरी करें और गेहूं की बुवाई की तैयारी करें।",
    ),
    "BEHROR_015": PanchayatMetadata(
        panchayat_id="BEHROR_015",
        name="Behror",
        name_hi="बहरोड़",
        district="Kotputli-Behror",
        block="Behror",
        latitude=27.89,
        longitude=76.28,
        elevation_m=360.0,
        crop="Mustard (RH-749)",
        crop_hi="सरसों",
        crop_stage="Vegetative",
        default_advisory_en="Optimal thermal window for high-yield RH-749 mustard sowing.",
        default_advisory_hi="सरसों की उन्नत किस्म RH-749 की बुवाई के लिए अनुकूल तापमान।",
    ),
    "TIJARA_016": PanchayatMetadata(
        panchayat_id="TIJARA_016",
        name="Tijara",
        name_hi="तिजारा",
        district="Khairthal-Tijara",
        block="Tijara",
        latitude=27.93,
        longitude=76.85,
        elevation_m=310.0,
        crop="Onion & Vegetables",
        crop_hi="सब्जियां",
        crop_stage="Vegetative",
        default_advisory_en="Avoid standing water in onion nurseries during humid mornings.",
        default_advisory_hi="प्याज की पौधशाला में जल भराव न होने दें।",
    ),
    "THANAGAZI_017": PanchayatMetadata(
        panchayat_id="THANAGAZI_017",
        name="Thanagazi",
        name_hi="थानागाजी",
        district="Alwar",
        block="Thanagazi",
        latitude=27.4,
        longitude=76.32,
        elevation_m=430.0,
        crop="Pearl Millet (Bajra)",
        crop_hi="बाजरा",
        crop_stage="Vegetative",
        default_advisory_en="Contour bunding recommended on Aravalli foot-slopes to conserve soil moisture.",
        default_advisory_hi="पहाड़ी ढलानों पर मिट्टी के कटाव को रोकने के लिए मेड़बंदी करें।",
    ),
    "BANDIKUI_018": PanchayatMetadata(
        panchayat_id="BANDIKUI_018",
        name="Bandikui",
        name_hi="बांदीकुई",
        district="Dausa",
        block="Bandikui",
        latitude=27.05,
        longitude=76.57,
        elevation_m=345.0,
        crop="Wheat (Raj 4037)",
        crop_hi="गेहूं",
        crop_stage="Vegetative",
        default_advisory_en="Plow fields 4-5 days post pre-sowing irrigation for fine seedbed.",
        default_advisory_hi="पलेवा (प्री-सोइंग सिंचाई) के 4-5 दिन बाद जुताई करें।",
    ),
    "LALSOT_019": PanchayatMetadata(
        panchayat_id="LALSOT_019",
        name="Lalsot",
        name_hi="लालसोट",
        district="Dausa",
        block="Lalsot",
        latitude=26.56,
        longitude=76.33,
        elevation_m=370.0,
        crop="Mustard (Giriraj)",
        crop_hi="सरसों",
        crop_stage="Vegetative",
        default_advisory_en="Apply single super phosphate (SSP) as basal dose for mustard.",
        default_advisory_hi="सरसों में फास्फोरस युक्त उर्वरक बेसल डोज के रूप में दें।",
    ),
    "KISHANGARH_020": PanchayatMetadata(
        panchayat_id="KISHANGARH_020",
        name="Kishangarh",
        name_hi="किशनगढ़",
        district="Ajmer",
        block="Kishangarh",
        latitude=26.57,
        longitude=74.87,
        elevation_m=455.0,
        crop="Sorghum (Jowar)",
        crop_hi="ज्वार",
        crop_stage="Vegetative",
        default_advisory_en="Harvest fodder sorghum; prepare land for rabi legumes.",
        default_advisory_hi="चारा फसलों की कटाई पूरी करें।",
    ),
    "SIRSA_021": PanchayatMetadata(
        panchayat_id="SIRSA_021",
        name="Sirsa",
        name_hi="सिरसा",
        district="Sirsa",
        block="Sirsa",
        latitude=29.535,
        longitude=75.03,
        elevation_m=205.0,
        crop="Bt Cotton (Bt-II)",
        crop_hi="कपास",
        crop_stage="Vegetative",
        default_advisory_en="Deep plow cotton fields after final harvest to destroy pink bollworm pupae.",
        default_advisory_hi="कपास की अंतिम चुगाई के बाद गुलाबी सुंडी नियंत्रण हेतु खेत की गहरी जुताई करें।",
    ),
    "FATEHABAD_022": PanchayatMetadata(
        panchayat_id="FATEHABAD_022",
        name="Fatehabad",
        name_hi="फतेहाबाद",
        district="Fatehabad",
        block="Fatehabad",
        latitude=29.51,
        longitude=75.45,
        elevation_m=214.0,
        crop="Wheat (WH 1105)",
        crop_hi="गेहूं",
        crop_stage="Vegetative",
        default_advisory_en="Direct drill wheat with Super Seeder for in-situ paddy straw mulching.",
        default_advisory_hi="सुपर सीडर या हैप्पी सीडर से धान की पराली प्रबंधन करते हुए गेहूं बोएं।",
    ),
    "HISAR_023": PanchayatMetadata(
        panchayat_id="HISAR_023",
        name="Hisar",
        name_hi="हिसार",
        district="Hisar",
        block="Hisar",
        latitude=29.15,
        longitude=75.72,
        elevation_m=215.0,
        crop="Gram / Mustard",
        crop_hi="चना",
        crop_stage="Vegetative",
        default_advisory_en="CCSHAU agromet advisory: Optimal sowing window active for rabi pulses.",
        default_advisory_hi="सीसीएस एचएयू सिफारिश: चने की बुवाई 25 अक्टूबर से 10 नवंबर तक पूरी करें।",
    ),
    "KARNAL_024": PanchayatMetadata(
        panchayat_id="KARNAL_024",
        name="Karnal",
        name_hi="करनाल",
        district="Karnal",
        block="Karnal",
        latitude=29.685,
        longitude=76.99,
        elevation_m=252.0,
        crop="Basmati Rice (PB 1121)",
        crop_hi="बासमती धान",
        crop_stage="Vegetative",
        default_advisory_en="Harvest Basmati at 18-20% grain moisture to prevent milling broken percentage.",
        default_advisory_hi="बासमती 1121 की कटाई 18-20% नमी पर करें ताकि दाना न टूटे।",
    ),
    "JIND_025": PanchayatMetadata(
        panchayat_id="JIND_025",
        name="Jind",
        name_hi="जींद",
        district="Jind",
        block="Jind",
        latitude=29.32,
        longitude=76.31,
        elevation_m=227.0,
        crop="Wheat (DBW 187)",
        crop_hi="गेहूं",
        crop_stage="Vegetative",
        default_advisory_en="Seedbed preparation for early sowing DBW 187 Karan Vandana wheat.",
        default_advisory_hi="करण वंदना (DBW 187) गेहूं की अगेती बुवाई हेतु खेत की तैयारी करें।",
    ),
    "LUDHIANA_026": PanchayatMetadata(
        panchayat_id="LUDHIANA_026",
        name="Ludhiana",
        name_hi="लुधियाना",
        district="Ludhiana",
        block="Ludhiana",
        latitude=30.9,
        longitude=75.857,
        elevation_m=247.0,
        crop="Wheat (PBW 826)",
        crop_hi="गेहूं",
        crop_stage="Vegetative",
        default_advisory_en="PAU Ludhiana advisory: Optimal thermal regime for PBW 826 wheat.",
        default_advisory_hi="पीएयू लुधियाना: पीबीडब्ल्यू 826 की बिजाई नवंबर के पहले पखवाड़े में करें।",
    ),
    "KHANNA_027": PanchayatMetadata(
        panchayat_id="KHANNA_027",
        name="Khanna",
        name_hi="खन्ना",
        district="Ludhiana",
        block="Khanna",
        latitude=30.7,
        longitude=76.22,
        elevation_m=255.0,
        crop="Wheat & Grain Market",
        crop_hi="गेहूं",
        crop_stage="Vegetative",
        default_advisory_en="Dry grain to 14% moisture before market arrival. Arrange DAP fertilizer for wheat.",
        default_advisory_hi="धान की उपज को सुखाकर ही मंडी में लाएं। गेहूं बिजाई के लिए डीएपी का प्रबंध करें।",
    ),
    "NABHA_028": PanchayatMetadata(
        panchayat_id="NABHA_028",
        name="Nabha",
        name_hi="नाभा",
        district="Patiala",
        block="Nabha",
        latitude=30.37,
        longitude=76.15,
        elevation_m=250.0,
        crop="Wheat (HD 3086)",
        crop_hi="गेहूं",
        crop_stage="Vegetative",
        default_advisory_en="Zero-till wheat sowing recommended to save fuel and soil moisture.",
        default_advisory_hi="जीरो टिलेज मशीन से गेहूं की बिजाई कर लागत और पानी बचाएं।",
    ),
    "BATHINDA_029": PanchayatMetadata(
        panchayat_id="BATHINDA_029",
        name="Bathinda",
        name_hi="बठिंडा",
        district="Bathinda",
        block="Bathinda",
        latitude=30.21,
        longitude=74.945,
        elevation_m=201.0,
        crop="Cotton / Mustard",
        crop_hi="कपास / सरसों",
        crop_stage="Vegetative",
        default_advisory_en="Sow RLC-3 Raya mustard immediately post cotton clearance.",
        default_advisory_hi="कपास के बाद सरसों की राया किस्मों (आरएलसी-3) की बिजाई करें।",
    ),
    "ABOHAR_030": PanchayatMetadata(
        panchayat_id="ABOHAR_030",
        name="Abohar",
        name_hi="अबोहर",
        district="Fazilka",
        block="Abohar",
        latitude=30.14,
        longitude=74.19,
        elevation_m=185.0,
        crop="Kinnow Citrus Orchards",
        crop_hi="किन्नू",
        crop_stage="Vegetative",
        default_advisory_en="Deploy fruit fly pheromone traps in Kinnow orchards. Maintain light irrigation.",
        default_advisory_hi="किन्नू में फल मक्खी के नियंत्रण हेतु फेरोमोन ट्रैप लगाएं। हल्की सिंचाई जारी रखें।",
    ),
    "AGRA_031": PanchayatMetadata(
        panchayat_id="AGRA_031",
        name="Agra",
        name_hi="आगरा",
        district="Agra",
        block="Bichpuri",
        latitude=27.176,
        longitude=78.008,
        elevation_m=169.0,
        crop="Potato (Kufri Bahar)",
        crop_hi="आलू",
        crop_stage="Vegetative",
        default_advisory_en="Optimal planting conditions for Kufri Bahar and Kufri Khyati seed potatoes.",
        default_advisory_hi="आलू की अगेती बुवाई के लिए कुफरी बहार या कुफरी ख्याति के कंदों का चयन करें।",
    ),
    "MEERUT_032": PanchayatMetadata(
        panchayat_id="MEERUT_032",
        name="Meerut",
        name_hi="मेरठ",
        district="Meerut",
        block="Daurala",
        latitude=28.984,
        longitude=77.706,
        elevation_m=219.0,
        crop="Sugarcane (Co 0238)",
        crop_hi="गन्ना",
        crop_stage="Vegetative",
        default_advisory_en="Autumn trench sugarcane planting with potato/mustard intercropping.",
        default_advisory_hi="शरदकालीन गन्ने की बुवाई 4 फीट की दूरी पर करें और साथ में सरसों या आलू की अंतरफसल लें।",
    ),
    "MUZAFFARNAGAR_033": PanchayatMetadata(
        panchayat_id="MUZAFFARNAGAR_033",
        name="Muzaffarnagar",
        name_hi="मुजफ्फरनगर",
        district="Muzaffarnagar",
        block="Khatauli",
        latitude=29.47,
        longitude=77.7,
        elevation_m=232.0,
        crop="Sugarcane (Co 15023)",
        crop_hi="गन्ना",
        crop_stage="Vegetative",
        default_advisory_en="Plant red-rot resistant Co 15023 sugarcane cultivars in trench beds.",
        default_advisory_hi="गन्ने की नई किस्म Co 15023 की बुवाई करें, लाल सड़न रोग से बचाव होगा।",
    ),
    "BARABANKI_034": PanchayatMetadata(
        panchayat_id="BARABANKI_034",
        name="Barabanki",
        name_hi="बाराबंकी",
        district="Barabanki",
        block="Fatehpur",
        latitude=26.93,
        longitude=81.18,
        elevation_m=125.0,
        crop="Mentha & Paddy",
        crop_hi="मेंथा / धान",
        crop_stage="Vegetative",
        default_advisory_en="Post-paddy field leveling for rabi mentha stolon nursery prep.",
        default_advisory_hi="धान की कटाई के बाद खेत को मेंथा की जड़ रोपाई के लिए तैयार करें।",
    ),
    "LUCKNOW_035": PanchayatMetadata(
        panchayat_id="LUCKNOW_035",
        name="Lucknow",
        name_hi="लखनऊ",
        district="Lucknow",
        block="Bakshi Ka Talab",
        latitude=26.846,
        longitude=80.946,
        elevation_m=123.0,
        crop="Mango Orchards (Dasheri)",
        crop_hi="आम / धान",
        crop_stage="Vegetative",
        default_advisory_en="Post-monsoon pruning and trunk wash in Malihabad mango belt.",
        default_advisory_hi="दशहरी आम के बागों में जाले की रोकथाम और थ्रिप्स कीट के लिए कीटनाशक का छिड़काव करें।",
    ),
    "VARANASI_036": PanchayatMetadata(
        panchayat_id="VARANASI_036",
        name="Varanasi",
        name_hi="वाराणसी",
        district="Varanasi",
        block="Kashi Vidyapeeth",
        latitude=25.317,
        longitude=82.973,
        elevation_m=81.0,
        crop="Vegetables & Paddy",
        crop_hi="सब्जियां",
        crop_stage="Vegetative",
        default_advisory_en="IIVR Varanasi: Transplant cabbage and cauliflower in raised beds.",
        default_advisory_hi="भारतीय सब्जी अनुसंधान संस्थान: पत्तागोभी और फूलगोभी की रोपाई का उचित समय।",
    ),
    "PATNA_037": PanchayatMetadata(
        panchayat_id="PATNA_037",
        name="Patna",
        name_hi="पटना",
        district="Patna",
        block="Phulwari Sharif",
        latitude=25.594,
        longitude=85.137,
        elevation_m=53.0,
        crop="Rabi Maize (Shaktiman)",
        crop_hi="मक्का",
        crop_stage="Vegetative",
        default_advisory_en="Rabi maize hybrid sowing window open; apply starter zinc sulphate.",
        default_advisory_hi="रबी मक्का (शक्तिमान 5) की बुवाई अक्टूबर के अंत से 15 नवंबर तक पूरी करें।",
    ),
    "SAMASTIPUR_038": PanchayatMetadata(
        panchayat_id="SAMASTIPUR_038",
        name="Samastipur",
        name_hi="समस्तीपुर",
        district="Samastipur",
        block="Pusa",
        latitude=25.86,
        longitude=85.78,
        elevation_m=52.0,
        crop="Tobacco & Maize",
        crop_hi="तम्बाकू / मक्का",
        crop_stage="Vegetative",
        default_advisory_en="RPCAU Pusa: Complete seed inoculation with Rhizobium culture.",
        default_advisory_hi="डॉ. राजेंद्र प्रसाद केंद्रीय कृषि विश्वविद्यालय: रबी फसलों के बीज शोधन पर ध्यान दें।",
    ),
    "NASHIK_039": PanchayatMetadata(
        panchayat_id="NASHIK_039",
        name="Nashik",
        name_hi="नासिक",
        district="Nashik",
        block="Niphad",
        latitude=20.08,
        longitude=74.11,
        elevation_m=585.0,
        crop="Export Grapes (Thompson Seedless)",
        crop_hi="अंगूर",
        crop_stage="Vegetative",
        default_advisory_en="Post-October forward pruning downy mildew preventive Bordeaux spray.",
        default_advisory_hi="ऑक्टोबर छाटणीनंतर डाउनी मिल्ड्यूच्या प्रतिबंधासाठी बोर्डो मिश्रणाची फवारणी करा.",
    ),
    "NIPHAD_040": PanchayatMetadata(
        panchayat_id="NIPHAD_040",
        name="Niphad",
        name_hi="निफाड",
        district="Nashik",
        block="Niphad",
        latitude=20.085,
        longitude=74.115,
        elevation_m=570.0,
        crop="Onion & Grapes",
        crop_hi="कांदा / द्राक्षे",
        crop_stage="Vegetative",
        default_advisory_en="Complete Rangda onion seedling transplanting; optimize drip intervals.",
        default_advisory_hi="रांगडा कांदा रोपांची पुनर्लागवड पूर्ण करा. ठिबक सिंचन चालू ठेवा.",
    ),
    "PUNE_041": PanchayatMetadata(
        panchayat_id="PUNE_041",
        name="Pune",
        name_hi="पुणे",
        district="Pune",
        block="Haveli",
        latitude=18.52,
        longitude=73.856,
        elevation_m=560.0,
        crop="Sugarcane & Floriculture",
        crop_hi="ऊस / भाजीपाला",
        crop_stage="Vegetative",
        default_advisory_en="Micronutrient foliar application for polyhouse floriculture.",
        default_advisory_hi="फुलशेतीमध्ये सूक्ष्म अन्नद्रव्यांची फवारणी करावी.",
    ),
    "BARAMATI_042": PanchayatMetadata(
        panchayat_id="BARAMATI_042",
        name="Baramati",
        name_hi="बारामती",
        district="Pune",
        block="Baramati",
        latitude=18.15,
        longitude=74.58,
        elevation_m=538.0,
        crop="Sugarcane (Co 86032)",
        crop_hi="ऊस",
        crop_stage="Vegetative",
        default_advisory_en="Apply second fertilizer split and earthing up in Adsali cane.",
        default_advisory_hi="अडसाली ऊसामध्ये खतांचा दुसरा हप्ता देऊन भर लावावी.",
    ),
    "JUNNAR_043": PanchayatMetadata(
        panchayat_id="JUNNAR_043",
        name="Junnar",
        name_hi="जुन्नर",
        district="Pune",
        block="Junnar",
        latitude=19.2,
        longitude=73.87,
        elevation_m=675.0,
        crop="Tomato & Exotic Veg",
        crop_hi="टोमॅटो",
        crop_stage="Vegetative",
        default_advisory_en="Scout for leaf minor and early blight in trellis tomato plots.",
        default_advisory_hi="टोमॅटो पिकात नागअळी आणि करपा नियंत्रणासाठी फवारणी करा.",
    ),
    "NAGPUR_044": PanchayatMetadata(
        panchayat_id="NAGPUR_044",
        name="Nagpur",
        name_hi="नागपुर",
        district="Nagpur",
        block="Katol",
        latitude=21.145,
        longitude=79.088,
        elevation_m=310.0,
        crop="Nagpur Mandarin Orange",
        crop_hi="संत्रा",
        crop_stage="Vegetative",
        default_advisory_en="Begin harvesting Mrig bahar mandarin oranges; grade for dispatch.",
        default_advisory_hi="मृग बहराच्या संत्रा फळांची तोडणी सुरू करावी.",
    ),
    "AHMEDABAD_045": PanchayatMetadata(
        panchayat_id="AHMEDABAD_045",
        name="Ahmedabad",
        name_hi="अहमदाबाद",
        district="Ahmedabad",
        block="Daskroi",
        latitude=23.022,
        longitude=72.571,
        elevation_m=53.0,
        crop="Cotton (Gujarat Hybrid-8)",
        crop_hi="કપાસ",
        crop_stage="Vegetative",
        default_advisory_en="Install pheromone traps for pink bollworm monitoring in cotton.",
        default_advisory_hi="કપાસમાં ગુલાબી ઇયળના નિયંત્રણ માટે ફેરોમોન ટ્રેપ લગાવો.",
    ),
    "ANAND_046": PanchayatMetadata(
        panchayat_id="ANAND_046",
        name="Anand",
        name_hi="आनंद",
        district="Anand",
        block="Anand",
        latitude=22.56,
        longitude=72.93,
        elevation_m=42.0,
        crop="Tobacco & Fodder",
        crop_hi="તમાકુ / ડેરી",
        crop_stage="Vegetative",
        default_advisory_en="Light irrigation post tobacco seedling transplanting.",
        default_advisory_hi="તમાકુની ફેરરોપણી બાદ હળવું પિયત આપવું.",
    ),
    "RAJKOT_047": PanchayatMetadata(
        panchayat_id="RAJKOT_047",
        name="Rajkot",
        name_hi="राजकोट",
        district="Rajkot",
        block="Gondal",
        latitude=22.303,
        longitude=70.802,
        elevation_m=128.0,
        crop="Groundnut (GG-20)",
        crop_hi="મગફળી",
        crop_stage="Vegetative",
        default_advisory_en="Sun-dry harvested groundnut pods to optimal 8% storage moisture.",
        default_advisory_hi="મગફળીનો ઉપાડ પૂર્ણ કરી સૂર્યપ્રકાશમાં સૂકવણી કરો.",
    ),
    "BHOPAL_048": PanchayatMetadata(
        panchayat_id="BHOPAL_048",
        name="Bhopal",
        name_hi="भोपाल",
        district="Bhopal",
        block="Phanda",
        latitude=23.259,
        longitude=77.412,
        elevation_m=527.0,
        crop="Soybean / Wheat (Sharbati)",
        crop_hi="सोयाबीन / गेहूं",
        crop_stage="Vegetative",
        default_advisory_en="Field preparation for premium Sharbati wheat post soybean threshing.",
        default_advisory_hi="सोयाबीन की गहाई के बाद शरबती गेहूं (C-306) की बुवाई की तैयारी करें।",
    ),
    "INDORE_049": PanchayatMetadata(
        panchayat_id="INDORE_049",
        name="Indore",
        name_hi="इंदौर",
        district="Indore",
        block="Sanwer",
        latitude=22.719,
        longitude=75.857,
        elevation_m=553.0,
        crop="Soybean & Kabuli Gram",
        crop_hi="सोयाबीन / चना",
        crop_stage="Vegetative",
        default_advisory_en="Pre-sowing irrigation for Dollar Kabuli chickpea planting.",
        default_advisory_hi="काबुली चना (डॉलर चना) की बुवाई के लिए खेत में पलेवा लगाएं।",
    ),
    "HOSHANGABAD_050": PanchayatMetadata(
        panchayat_id="HOSHANGABAD_050",
        name="Hoshangabad",
        name_hi="होशंगाबाद",
        district="Narmadapuram",
        block="Hoshangabad",
        latitude=22.75,
        longitude=77.72,
        elevation_m=290.0,
        crop="Narmada Valley Wheat",
        crop_hi="गेहूं",
        crop_stage="Vegetative",
        default_advisory_en="Sow high-protein JW 3288 wheat in fertile Narmada alluvium.",
        default_advisory_hi="नर्मदा घाटी: गेहूं की उन्नत किस्म जेडब्ल्यू 3288 की बुवाई करें।",
    ),
    "RAIPUR_051": PanchayatMetadata(
        panchayat_id="RAIPUR_051",
        name="Raipur",
        name_hi="रायपुर",
        district="Raipur",
        block="Dharsiwa",
        latitude=21.251,
        longitude=81.629,
        elevation_m=298.0,
        crop="Paddy (Swarna / Mahamaya)",
        crop_hi="धान",
        crop_stage="Vegetative",
        default_advisory_en="Begin harvesting Swarna paddy when 80% panicles turn golden.",
        default_advisory_hi="धान की स्वर्णा किस्म की कटाई 80% दाना पकने पर करें।",
    ),
    "BENGALURU_052": PanchayatMetadata(
        panchayat_id="BENGALURU_052",
        name="Bengaluru",
        name_hi="बेंगलुरु",
        district="Bengaluru Rural",
        block="Doddaballapur",
        latitude=12.971,
        longitude=77.594,
        elevation_m=920.0,
        crop="Finger Millet (Ragi - ML 365)",
        crop_hi="ರಾಗಿ",
        crop_stage="Vegetative",
        default_advisory_en="Light irrigation during Ragi grain filling stage for plump grains.",
        default_advisory_hi="ರಾಗಿ ಬೆಳೆಯಲ್ಲಿ ತೆನೆ ತುಂಬುವ ಹಂತದಲ್ಲಿದ್ದು ಹಗುರ ನೀರಾವರಿ ಒದಗಿಸಿ.",
    ),
    "JODHPUR_053": PanchayatMetadata(
        panchayat_id="JODHPUR_053",
        name="Jodhpur",
        name_hi="जोधपुर",
        district="Jodhpur",
        block="Mandore",
        latitude=26.238,
        longitude=73.024,
        elevation_m=231.0,
        crop="Cumin & Pearl Millet",
        crop_hi="बाजरा / जीरा",
        crop_stage="Vegetative",
        default_advisory_en="CAZRI guidance: Field preparation & Trichoderma seed treatment for cumin.",
        default_advisory_hi="काजरी सिफारिश: जीरे की बुवाई के लिए खेत तैयार करें व ट्राइकोडर्मा से उपचारित करें।",
    ),
    "BIKANER_054": PanchayatMetadata(
        panchayat_id="BIKANER_054",
        name="Bikaner",
        name_hi="बीकानेर",
        district="Bikaner",
        block="Napasar",
        latitude=28.022,
        longitude=73.311,
        elevation_m=242.0,
        crop="Groundnut & Moth Bean",
        crop_hi="मूंगफली / मोठ",
        crop_stage="Vegetative",
        default_advisory_en="Maintain micro-irrigation regime for desert sandy loam groundnut.",
        default_advisory_hi="रेगिस्तानी रेतीली मिट्टी में ड्रिप से मूंगफली में हल्की सिंचाई जारी रखें।",
    ),
    "GORAKHPUR_055": PanchayatMetadata(
        panchayat_id="GORAKHPUR_055",
        name="Gorakhpur",
        name_hi="गोरखपुर",
        district="Gorakhpur",
        block="Pipraich",
        latitude=26.76,
        longitude=83.373,
        elevation_m=84.0,
        crop="Sugarcane & Terai Paddy",
        crop_hi="गन्ना / धान",
        crop_stage="Vegetative",
        default_advisory_en="Terai zone: Prop sugarcane stalks and maintain field drainage trenches.",
        default_advisory_hi="तराई क्षेत्र: गन्ने की अगेती किस्मों की बंधाई और जल निकासी दुरुस्त रखें।",
    ),
    "JHANSI_056": PanchayatMetadata(
        panchayat_id="JHANSI_056",
        name="Jhansi",
        name_hi="झांसी",
        district="Jhansi",
        block="Babina",
        latitude=25.448,
        longitude=78.568,
        elevation_m=284.0,
        crop="Bundelkhand Chickpea & Sesame",
        crop_hi="चना / तिल",
        crop_stage="Vegetative",
        default_advisory_en="Bundelkhand agromet: Complete timely sowing for drought-hardy chickpea.",
        default_advisory_hi="बुंदेलखंड कृषि अनुसंधान: कम पानी वाले चने की बुवाई समय से पूरी करें।",
    ),
    "MUZAFFARPUR_057": PanchayatMetadata(
        panchayat_id="MUZAFFARPUR_057",
        name="Muzaffarpur",
        name_hi="मुजफ्फरपुर",
        district="Muzaffarpur",
        block="Kanti",
        latitude=26.12,
        longitude=85.364,
        elevation_m=60.0,
        crop="Shahi Litchi & Winter Maize",
        crop_hi="शाही लीची / मक्का",
        crop_stage="Vegetative",
        default_advisory_en="Apply neem oil spray in Shahi Litchi orchards for stem borer defense.",
        default_advisory_hi="लीची के बागों में जाले व कीटों से सुरक्षा हेतु नीम तेल का छिड़काव करें।",
    ),
    "CUTTACK_058": PanchayatMetadata(
        panchayat_id="CUTTACK_058",
        name="Cuttack",
        name_hi="कटक",
        district="Cuttack",
        block="Salepur",
        latitude=20.462,
        longitude=85.882,
        elevation_m=36.0,
        crop="CRRI Coastal Paddy (Pooja)",
        crop_hi="ଧାନ",
        crop_stage="Vegetative",
        default_advisory_en="NRRI advisory: Monitor rice gundhi bug in late maturing coastal paddy.",
        default_advisory_hi="ସି.ଆର.ଆର.ଆଇ ପରାମର୍ଶ: ପୂଜା ଧାନ ଫସଲରେ ଗନ୍ଧି ପୋକ ନିୟନ୍ତ୍ରଣ ପାଇଁ ଧ୍ୟାନ ଦିଅନ୍ତୁ।",
    ),
    "SURAT_059": PanchayatMetadata(
        panchayat_id="SURAT_059",
        name="Surat",
        name_hi="सूरत",
        district="Surat",
        block="Bardoli",
        latitude=21.17,
        longitude=72.831,
        elevation_m=13.0,
        crop="Sugarcane & Hybrid Cotton",
        crop_hi="શેરડી / કપાસ",
        crop_stage="Vegetative",
        default_advisory_en="South Gujarat: Fertigation via drip in high-yield sugarcane crop.",
        default_advisory_hi="દક્ષિણ ગુજરાત: શેરડીમાં ટપક સિંચાઈ વડે પોષક તત્વોનું વ્યવસ્થાપન કરો.",
    ),
    "WARANGAL_060": PanchayatMetadata(
        panchayat_id="WARANGAL_060",
        name="Warangal",
        name_hi="वारंगल",
        district="Warangal",
        block="Hanamkonda",
        latitude=17.968,
        longitude=79.594,
        elevation_m=266.0,
        crop="Telangana Red Cotton & Chilli",
        crop_hi="పత్తి / మిర్చి",
        crop_stage="Vegetative",
        default_advisory_en="Set pheromone traps for pink bollworm management in cotton.",
        default_advisory_hi="పత్తిలో గులాబీ రంగు పురుగు నివారణకు లింగాకర్షక బుట్టలను అమర్చండి.",
    ),
    "SHIMOGA_061": PanchayatMetadata(
        panchayat_id="SHIMOGA_061",
        name="Shimoga",
        name_hi="शिवमोग्गा",
        district="Shimoga",
        block="Bhadravati",
        latitude=13.929,
        longitude=75.568,
        elevation_m=569.0,
        crop="Arecanut & Malnad Paddy",
        crop_hi="ಅಡಿಕೆ / ಭತ್ತ",
        crop_stage="Vegetative",
        default_advisory_en="Malnad region: Apply 1% Bordeaux mixture to prevent fruit rot in Arecanut.",
        default_advisory_hi="ಮಲೆನಾಡು: ಅಡಿಕೆ ತೋಟಗಳಲ್ಲಿ ಕೊಳೆ ರೋಗ ತಡೆಗಟ್ಟಲು ಬೋರ್ಡೋ ಮಿಶ್ರಣ ಸಿಂಪಡಿಸಿ.",
    ),
    "MADURAI_062": PanchayatMetadata(
        panchayat_id="MADURAI_062",
        name="Madurai",
        name_hi="मदुरै",
        district="Madurai",
        block="Melur",
        latitude=9.925,
        longitude=78.119,
        elevation_m=136.0,
        crop="Madurai Jasmine & Rice",
        crop_hi="மல்லிகை / நெல்",
        crop_stage="Vegetative",
        default_advisory_en="Monitor bud worm vectors in GI-tagged Madurai Malli jasmine.",
        default_advisory_hi="மல்லிகைத் தோட்டங்களில் மொட்டுப்புழு தாக்கத்தைக் கண்காணிக்கவும்.",
    ),
    "SRINAGAR_063": PanchayatMetadata(
        panchayat_id="SRINAGAR_063",
        name="Srinagar",
        name_hi="श्रीनगर",
        district="Srinagar",
        block="Shalteng",
        latitude=34.083,
        longitude=74.797,
        elevation_m=1585.0,
        crop="Kashmir Apple & Saffron (Pampore)",
        crop_hi="سیب / زعفران",
        crop_stage="Vegetative",
        default_advisory_en="Kashmir Valley: Pluck Pampore saffron flowers early morning to preserve safranal aroma.",
        default_advisory_hi="कश्मीर घाटी: पाम्पोर में केसर के फूलों की तुड़ाई सुबह के समय पूरी करें।",
    ),
    "LEH_064": PanchayatMetadata(
        panchayat_id="LEH_064",
        name="Leh",
        name_hi="लेह",
        district="Leh",
        block="Chuchot",
        latitude=34.152,
        longitude=77.577,
        elevation_m=3500.0,
        crop="Ladakh Apricot & Seabuckthorn",
        crop_hi="गुलदाउदी / खुबानी",
        crop_stage="Vegetative",
        default_advisory_en="Trans-Himalaya: Insulate passive solar greenhouses against extreme sub-zero night dips.",
        default_advisory_hi="लद्दाख ट्रांस-हिमालय: पॉलीथिन ग्रीनहाउस में सब्जियों को रात के पाले से बचाएं।",
    ),
    "MANDYA_065": PanchayatMetadata(
        panchayat_id="MANDYA_065",
        name="Mandya",
        name_hi="मांड्या",
        district="Mandya",
        block="Maddur",
        latitude=12.52,
        longitude=76.89,
        elevation_m=678.0,
        crop="Sugarcane & Paddy",
        crop_hi="ಕಬ್ಬು",
        crop_stage="Vegetative",
        default_advisory_en="Cauvery basin: Weed management and timely fertigation for cane.",
        default_advisory_hi="ಕಾವೇರಿ ಜಲಾನಯನ: ಕಬ್ಬಿನ ಬೆಳೆಗೆ ಕಳೆ ನಿಯಂತ್ರಣ ಮತ್ತು ರಸಗೊಬ್ಬರ ನಿರ್ವಹಣೆ.",
    ),
    "HYDERABAD_066": PanchayatMetadata(
        panchayat_id="HYDERABAD_066",
        name="Hyderabad",
        name_hi="हैदराबाद",
        district="Hyderabad",
        block="Rajendranagar",
        latitude=17.385,
        longitude=78.486,
        elevation_m=542.0,
        crop="Cotton & Maize",
        crop_hi="పత్తి / వరి",
        crop_stage="Vegetative",
        default_advisory_en="Spray Copper Oxychloride for bacterial leaf spot in red soil cotton.",
        default_advisory_hi="పత్తి చేనులో ఆకుమచ్చ తెగులు నివారణకు కాపర్ ఆక్సీక్లోరైడ్ పిచికారీ చేయండి.",
    ),
    "GUNTUR_067": PanchayatMetadata(
        panchayat_id="GUNTUR_067",
        name="Guntur",
        name_hi="गुंटूर",
        district="Guntur",
        block="Tenali",
        latitude=16.306,
        longitude=80.436,
        elevation_m=33.0,
        crop="Red Chilli (Guntur Sannam)",
        crop_hi="మిర్చి",
        crop_stage="Vegetative",
        default_advisory_en="Monitor invasive thrips vectors in export-grade Guntur red chilli.",
        default_advisory_hi="మిర్చి తోటల్లో తామర పురుగు (థ్రిప్స్) ఉధృతిని గమనించి నివారణ చర్యలు చేపట్టండి.",
    ),
    "COIMBATORE_068": PanchayatMetadata(
        panchayat_id="COIMBATORE_068",
        name="Coimbatore",
        name_hi="कोयंबटूर",
        district="Coimbatore",
        block="Pollachi",
        latitude=11.016,
        longitude=76.955,
        elevation_m=411.0,
        crop="Coconut & Cotton",
        crop_hi="தென்னை",
        crop_stage="Vegetative",
        default_advisory_en="Erect yellow sticky traps for rugose spiraling whitefly in coconut.",
        default_advisory_hi="தென்னந்தோப்புகளில் வெள்ளை ஈ தாக்குதலைக் கட்டுப்படுத்த மஞ்சள் ஒட்டும் பொறிகளை அமைக்கவும்.",
    ),
    "THANJAVUR_069": PanchayatMetadata(
        panchayat_id="THANJAVUR_069",
        name="Thanjavur",
        name_hi="तंजாவூர்",
        district="Thanjavur",
        block="Papanasam",
        latitude=10.786,
        longitude=79.137,
        elevation_m=57.0,
        crop="Samba Paddy (CR 1009)",
        crop_hi="நெல்",
        crop_stage="Vegetative",
        default_advisory_en="Cauvery Delta: Maintain field drainage channels for Samba paddy.",
        default_advisory_hi="காவிரி டெல்டா: சம்பா நெல் வயல்களில் வடிகால் வசதியை உறுதி செய்யவும்.",
    ),
    "PALAKKAD_070": PanchayatMetadata(
        panchayat_id="PALAKKAD_070",
        name="Palakkad",
        name_hi="पालक्काड",
        district="Palakkad",
        block="Chittur",
        latitude=10.786,
        longitude=76.654,
        elevation_m=84.0,
        crop="Palakkad Matta Rice",
        crop_hi="നെല്ല്",
        crop_stage="Vegetative",
        default_advisory_en="Bacterial leaf blight watch in second crop Mundakan Matta paddy.",
        default_advisory_hi="മുണ്ടകൻ നെല്ല് പാടങ്ങളിൽ ഇലകരിച്ചിൽ രോഗത്തിനെതിരെ ജാഗ്രത പാലിക്കുക.",
    ),
    "KANGRA_071": PanchayatMetadata(
        panchayat_id="KANGRA_071",
        name="Kangra",
        name_hi="कांगड़ा",
        district="Kangra",
        block="Dharamshala",
        latitude=32.099,
        longitude=76.269,
        elevation_m=733.0,
        crop="Kangra Tea & Wheat",
        crop_hi="चाय / सेब",
        crop_stage="Vegetative",
        default_advisory_en="Cold air drainage watch; prepare bushes for winter resting prune.",
        default_advisory_hi="कांगड़ा घाटी: चाय के बागानों में सर्दियों की छंटाई की तैयारी करें।",
    ),
    "SUNDLA_072": PanchayatMetadata(
        panchayat_id="SUNDLA_072",
        name="Sundla",
        name_hi="सुंडला",
        district="Kangra",
        block="Palampur",
        latitude=32.12,
        longitude=76.54,
        elevation_m=1246.0,
        crop="Hill Wheat & Exotic Veg",
        crop_hi="गेहूं",
        crop_stage="Vegetative",
        default_advisory_en="Nocturnal inversion alert: cover high-altitude seedbeds from frost.",
        default_advisory_hi="रात के समय पाले (Frost) से बचाव हेतु नर्सरी को पॉलीथिन से ढकें।",
    ),
    "DEHRADUN_073": PanchayatMetadata(
        panchayat_id="DEHRADUN_073",
        name="Dehradun",
        name_hi="देहरादून",
        district="Dehradun",
        block="Vikasnagar",
        latitude=30.316,
        longitude=78.032,
        elevation_m=640.0,
        crop="Dehradun Type 3 Basmati",
        crop_hi="बासमती",
        crop_stage="Vegetative",
        default_advisory_en="Doon Valley: Complete Type-3 Basmati harvest before frost onset.",
        default_advisory_hi="दून घाटी: सुगंधित बासमती की कटाई पूरी करें।",
    ),
    "GUWAHATI_074": PanchayatMetadata(
        panchayat_id="GUWAHATI_074",
        name="Guwahati",
        name_hi="गुवाहाटी",
        district="Kamrup",
        block="Hajo",
        latitude=26.144,
        longitude=91.736,
        elevation_m=55.0,
        crop="Assam Tea & Sali Paddy",
        crop_hi="চাহ / ধান",
        crop_stage="Vegetative",
        default_advisory_en="Initiate timely harvesting for early maturing Sali paddy.",
        default_advisory_hi="শালি ধানৰ পথাৰত শস্য কটাৰ কাম আৰম্ভ কৰক।",
    ),
    "JORHAT_075": PanchayatMetadata(
        panchayat_id="JORHAT_075",
        name="Jorhat",
        name_hi="जोरहाट",
        district="Jorhat",
        block="Titabor",
        latitude=26.75,
        longitude=94.2,
        elevation_m=87.0,
        crop="Assam Orthodox Tea",
        crop_hi="চাহ",
        crop_stage="Vegetative",
        default_advisory_en="TRA Tocklai guidance: Complete autumn plucking cycle.",
        default_advisory_hi="টোকলাই চাহ গৱেষণা প্ৰতিষ্ঠান: পাত তোলাৰ কাম নিয়মীয়া কৰক।",
    ),
}

# Alias map for case-insensitive and plain-name lookups (e.g. "shahpura" -> "SHAHPURA_009")
_ALIAS_MAP: dict[str, str] = {}
for pid, meta in PANCHAYAT_REGISTRY.items():
    _ALIAS_MAP[pid.lower()] = pid
    _ALIAS_MAP[meta.name.lower()] = pid
    _ALIAS_MAP[meta.name_hi] = pid
    base_key = pid.rsplit("_", 1)[0].lower()
    _ALIAS_MAP[base_key] = pid


def get_panchayat(identifier: str) -> PanchayatMetadata | None:
    """
    Look up a panchayat by canonical ID (e.g. "KADERA_001", "SHAHPURA_009") or name alias ("Shahpura", "shahpura").
    """
    if not identifier:
        return None
    cleaned = identifier.strip().lower()
    canonical_id = _ALIAS_MAP.get(cleaned)
    if canonical_id and canonical_id in PANCHAYAT_REGISTRY:
        return PANCHAYAT_REGISTRY[canonical_id]
    if identifier.strip().upper() in PANCHAYAT_REGISTRY:
        return PANCHAYAT_REGISTRY[identifier.strip().upper()]
    return None


def list_panchayats() -> list[PanchayatMetadata]:
    """Return canonical pilot panchayats in order."""
    return [PANCHAYAT_REGISTRY[pid] for pid in PILOT_PANCHAYAT_IDS if pid in PANCHAYAT_REGISTRY]


def list_all_panchayats() -> list[PanchayatMetadata]:
    """Return all registered pilot and multi-region panchayats."""
    return list(PANCHAYAT_REGISTRY.values())
